### ISSUE TITLE
bug: Optional values in fixed length arrays not supported

### ISSUE THREAD

**Issue by Shinigami92** [gristlabs/ts-interface-builder#16]
### Command

`yarn ts-interface-builder src/components/folder/folder/PreviewTextAdModel.ts`

### Error

```shell
yarn run v1.17.3
$ /Users/folder/folder/folder/folder/node_modules/.bin/ts-interface-builder src/components/folder/folder/PreviewTextAdModel.ts
/Users/folder/folder/folder/folder/node_modules/ts-interface-builder/dist/index.js:85
        throw new Error(`Node ${ts.SyntaxKind[node.kind]} not supported by ts-interface-builder: ` +
        ^

Error: Node JSDocNullableType not supported by ts-interface-builder: string?
    at Compiler.compileNode (/Users/folder/folder/folder/folder/node_modules/ts-interface-builder/dist/index.js:85:15)
    at Array.map (<anonymous>)
    at Compiler._compileTupleTypeNode (/Users/folder/folder/folder/folder/node_modules/ts-interface-builder/dist/index.js:148:43)
    at Compiler.compileNode (/Users/folder/folder/folder/folder/node_modules/ts-interface-builder/dist/index.js:51:55)
    at Compiler.compileOptType (/Users/folder/folder/folder/folder/node_modules/ts-interface-builder/dist/index.js:89:32)
    at Compiler._compilePropertySignature (/Users/folder/folder/folder/folder/node_modules/ts-interface-builder/dist/index.js:101:27)
    at Compiler.compileNode (/Users/folder/folder/folder/folder/node_modules/ts-interface-builder/dist/index.js:45:63)
    at /Users/folder/folder/folder/folder/node_modules/ts-interface-builder/dist/index.js:167:30
    at Array.map (<anonymous>)
    at Compiler._compileInterfaceDeclaration (/Users/folder/folder/folder/folder/node_modules/ts-interface-builder/dist/index.js:167:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Interface

```ts
interface PreviewTextAdModel {
  finalUrl: string;
  host: string;
  headlines: [string, string, string?];
  paths: [string?, string?];
  descriptions: [string, string?];
}
```

### Problem

`[string, string, string?]` => 0: string, 1: string, 2: string or **undefined**

### Current "workaround"

```ts
interface PreviewTextAdModel {
  finalUrl: string;
  host: string;
  headlines: [string, string] | [string, string, string];
  paths: [] | [string] | [string, string];
  descriptions: [string] | [string, string];
}
```

Produces

`PreviewTextAdModel-ti.ts`
```ts
/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
// tslint:disable:object-literal-key-quotes

export const PreviewTextAdModel = t.iface([], {
  finalUrl: 'string',
  host: 'string',
  headlines: t.union(t.tuple('string', 'string'), t.tuple('string', 'string', 'string')),
  paths: t.union(t.tuple(), t.tuple('string'), t.tuple('string', 'string')),
  descriptions: t.union(t.tuple('string'), t.tuple('string', 'string'))
});

const exportedTypeSuite: t.ITypeSuite = {
  PreviewTextAdModel
};
export default exportedTypeSuite;
```

**Comment by Shinigami92** [comment]
I tested `[string, string, string | undefined]` instead of `[string, string, string?]` and this is working!

Result is `t.tuple("string", "string", t.union("string", "undefined"))`

So maybe we only need to support the question mark syntax?

**BUT** attantion: it seams that it is not the same!
When I write `[string?, string | undefined]` I get a TypeScript ERROR `A required element cannot follow an optional element.ts (1257)`

![image](https://user-images.githubusercontent.com/7195563/63581913-54ce0700-c598-11e9-8fe9-01a3987ea37b.png)

`[string | undefined, string | undefined]` throws no errors and is valid syntax
![image](https://user-images.githubusercontent.com/7195563/63581982-7b8c3d80-c598-11e9-9bef-8279db49904d.png)

So it seam that `string?` is not the same as `string | undefined`. `string?` should mean: "Can be omitted"!

**Comment by Shinigami92** [comment]
When will there be the next release?

**Comment by Shinigami92** [comment]
Uhm, can you please also release `ts-interface-checker`?

**Comment by Shinigami92** [comment]
Thanks mate 👍
